wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    code_path: code/pytorchDQN.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.1
    start_time: 1668183900.214743
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.10.1
      5: 0.13.3
      8:
      - 3
      - 5
